---
- name: Test
  hosts: all
  vars:
    aws_region: us-east-1
  tasks:
  - name: mytest vpc
    ec2_vpc_net:
      name: VPC_tower_my
      cidr_block: 10.0.0.0/16
      region: "{{ aws_region }}"
      tenancy: default
    register: VPC_tower
    
  - name: Subnet_ec2
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ VPC_tower.vpc.id }}"
      cidr: 10.0.1.0/24
      region: "{{ aws_region }}"
    register: subnet_tower
    
  - name: create ec2    
    ec2:
      region: "{{ aws_region }}"
      key_name: hello
      instance_type: t2.micro
      image: ami-0aeeebd8d2ab47354
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet_tower.subnet.id }}"
      assign_public_ip: yes
